name: chatapploydlab
description: Chat Application example.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Firebase Packages
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_storage: ^8.0.0
  firebase_auth: ^1.0.1

  #Notification Pacakges
  firebase_messaging: ^9.0.0
  flutter_local_notifications: ^5.0.0-nullsafety.1
  flutter_app_badger: ^1.2.0

  #Image pick from library, crop image after pick image.
  image_picker: ^0.7.2+1
  image_cropper: ^1.4.0
  cached_network_image: ^3.0.0-nullsafety
  photo_view: ^0.11.1
  font_awesome_flutter: ^9.0.0-nullsafety

  #ETC
  shared_preferences: ^2.0.4
  url_launcher: ^6.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - images/youtube_screenshot.png